# Tensor Flow
텐서 플로우에 대해 배운다.

In [ ]:
import tensorflow as tf

In [ ]:
data = [
    [1,2],
    [3,4]
]
x = tf.constant(data)
print(x)

# tf.Tensor(
# [[1 2]
#  [3 4]], shape=(2, 2), dtype=int32)

In [ ]:
print(tf.rank(x))

# tf.Tensor(2, shape=(), dtype=int32)

In [ ]:
data = tf.constant("String")
print(data)

# tf.Tensor(b'String', shape=(), dtype=string)

In [ ]:
a = tf.constant([5])
b = tf.constant([6])

c = (a + b).numpy()
print(c)
print(type(c))
# [11]
# <class 'numpy.ndarray'>

In [ ]:
result = c * 10
tensor = tf.convert_to_tensor(result)
print(tensor)
print(type(tensor))
# tf.Tensor([110], shape=(1,), dtype=int32)
# <class 'tensorflow.python.framework.ops.EagerTensor'>

In [ ]:
x = tf.constant([
    [5,7],
    [1,0]
])

x_ones = tf.ones_like(x)
print(x_ones)

# tf.Tensor(
# [[1 1]
#  [1 1]], shape=(2, 2), dtype=int32)

In [ ]:
x_rand = tf.random.uniform(shape=x.shape, dtype = tf.int32, maxval=32)
print(x_rand)

# tf.Tensor(
# [[14  9]
#  [27 10]], shape=(2, 2), dtype=int32)

In [ ]:
tensor = tf.constant([
    [1,2,3,4],
    [2,4,5,6],
    [6,5,4,3]
])

print(tensor[0])
# tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
print(tensor[:, 0])     # ':'을 통해 행에 대해서 다 가져옴
# tf.Tensor([1 2 6], shape=(3,), dtype=int32)
print(tensor[..., -1])  # '...'을 통해 앞의 모든 원소를 다 가져옴
# tf.Tensor([4 6 3], shape=(3,), dtype=int32)

In [ ]:
result = tf.concat([tensor, tensor, tensor], axis = 0)
print(result)

# tf.Tensor(
# [[1 2 3 4]
#  [2 4 5 6]
#  [6 5 4 3]
#  [1 2 3 4]
#  [2 4 5 6]
#  [6 5 4 3]
#  [1 2 3 4]
#  [2 4 5 6]
#  [6 5 4 3]], shape=(9, 4), dtype=int32)

In [ ]:
result = tf.concat([tensor, tensor, tensor], axis = 1)
print(result)

# tf.Tensor(
# [[1 2 3 4 1 2 3 4 1 2 3 4]
#  [2 4 5 6 2 4 5 6 2 4 5 6]
#  [6 5 4 3 6 5 4 3 6 5 4 3]], shape=(3, 12), dtype=int32)

In [ ]:
a = tf.constant([2])
b = tf.constant([5.0])

print(a.dtype)
print(b.dtype)

print(tf.cast(a, tf.float32) + b)

# <dtype: 'int32'>
# <dtype: 'float32'>
# tf.Tensor([7.], shape=(1,), dtype=float32)

In [ ]:
a = tf.Variable([1,2,3,4,5,6,7,8])
b = tf.reshape(a, (4,2))
print(b)

# tf.Tensor(
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]], shape=(4, 2), dtype=int32)

In [ ]:
a.assign_add([1,1,1,1,1,1,1,1])
print(a)
print(b)

# <tf.Variable 'Variable:0' shape=(8,) dtype=int32, numpy=array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>
# tf.Tensor(
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]], shape=(4, 2), dtype=int32)

In [ ]:
a = tf.random.uniform((64,32,3))

print(a.shape)
# (64, 32, 3)

b = tf.transpose(a, perm = [2,1,0])
print(b.shape)

# (64, 32, 3)
# (3, 32, 64)

In [ ]:
a = tf.constant([
    [1,2],
    [3,4]
])
b = tf.constant([
    [5,6],
    [7,8]
])

print(a + b)
# tf.Tensor(
# [[ 6  8]
#  [10 12]], shape=(2, 2), dtype=int32)
print(a - b)
# tf.Tensor(
# [[-4 -4]
#  [-4 -4]], shape=(2, 2), dtype=int32)
print(a * b)
# tf.Tensor(
# [[ 5 12]
#  [21 32]], shape=(2, 2), dtype=int32)
print(a / b)
# tf.Tensor(
# [[0.2        0.33333333]
#  [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)

In [ ]:
print(tf.matmul(a,b))
# tf.Tensor(
# [[19 22]
#  [43 50]], shape=(2, 2), dtype=int32)

In [ ]:
a = tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])

print(a)
# tf.Tensor(
# [[1 2 3 4]
#  [5 6 7 8]], shape=(2, 4), dtype=int32)
print(tf.reduce_mean(a))# 전체 원소에 대한 평균
# tf.Tensor(4, shape=(), dtype=int32)
print(tf.reduce_mean(a, axis=0)) # 각 행의 평균
# tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
print(tf.reduce_mean(a, axis=1)) # 각 열의 평균
# tf.Tensor([2 6], shape=(2,), dtype=int32)

In [ ]:
print(tf.argmax(a, axis = 0))
print(tf.argmax(a, axis = 1))
# tf.Tensor([1 1 1 1], shape=(4,), dtype=int64)
# tf.Tensor([3 3], shape=(2,), dtype=int64)

In [ ]:
a = tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])

print(a.shape)
# (2, 4)
a = tf.expand_dims(a, 0)
print(a.shape)
# (1, 2, 4)
a = tf.expand_dims(a, 3)
print(a.shape)
# (1, 2, 4, 1)

In [ ]:
a = tf.squeeze(a)
print(a)
print(a.shape)

# tf.Tensor(
# [[1 2 3 4]
#  [5 6 7 8]], shape=(2, 4), dtype=int32)
# (2, 4)

In [ ]:
x = tf.Variable([3.0, 4.0])
y = tf.Variable([1.0, 2.0])

with tf.GradientTape() as tape:
    z = x + y
    loss = tf.math.reduce_mean(z)

dx = tape.gradient(loss, x)
print(dx)

# tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)

In [ ]:
x = tf.linspace(-10, 10, 100)
with tf.GradientTape() as tape:
    tape.watch(x) #constant이므로 watch()함수 호출
    y = tf.nn.sigmoid(x)

dx = tape.gradient(y,x)

import matplotlib.pyplot as plt

plt.plot(x,y, 'r', label = 'y')
plt.plot(x, dx, 'b--', label = 'dy/dx')
plt.legend()
plt.show()

In [ ]:
impro